version: '3.8'
services:
  db:
    image: postgres:15.4-alpine3.18
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    depends_on:
      - db
    ports:
      - '10000:10000'
    networks:
      - mynetwork

volumes:
  db:
    driver: local

networks:
  mynetwork:


