create table address
(
    id       bigint generated by default as identity primary key,
    address  varchar(255),
    city     varchar(255),
    country  varchar(255),
    postcode varchar(255),
    user_id  bigint references users
);